version: '3.8'
services:
  master:
    build:
      context: .
      dockerfile: ./Dockerfile.master
    working_dir: /root/playbooks
    volumes:
      - /c/repos/ansible/playbooks:/root/playbooks
      - /c/repos/ansible/config:/etc/ansible
    command: tail -f /dev/null
    
  web:
    build:
      context: .
      dockerfile: ./Dockerfile.server

